[package]
name = "mrt-check"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "mrt-check"
path = "src/main.rs"

[[bin]]
name = "mrt-run"
path = "src/run.rs"

[[bin]]
name = "mrt"
path = "src/run.rs"

[dependencies]
mrt-diagnostics = { path = "../crates/mrt-diagnostics" }
mrt-lexer = { path = "../crates/mrt-lexer" }
mrt-ast = { path = "../crates/mrt-ast" }
mrt-parser = { path = "../crates/mrt-parser" }
mrt-resolver = { path = "../crates/mrt-resolver" }
mrt-interp = { path = "../crates/mrt-interp" }

[lints]
workspace = true
